CREATE TABLE CALIFICACIONES(
ID_CALIFICACION integer,
MATERIA varchar2(80),
VALOR float,
constraint Pk_id_cal primary key(ID_CALIFICACION)
);

--GENERAR UNA SECUENCIA 
CREATE sequence SEC_CALIFICACIONES
start WITH 1
increment BY 1
nomaxvalue;

--AQUI VA EL PROCEDIMIENTO 
CREATE OR REPLACE PROCEDURE GUARDAR_CALIFICACIONES(
MY_ID_CALIFICACIONES OUT INTEGER,
MY_MATERIA IN  varchar2,
MY_VALOR IN float
)
AS 
BEGIN 
SELECT SEC_CALIFICACIONES.NEXTVAL INTO MY_ID_CALIFICACIONES FROM DUAL;
insert INTO CALIFICACIONES VALUES(MY_ID_CALIFICACIONES,MY_MATERIA,MY_VALOR);
END;
/

--PROBAR EL PROCEDIMIENTO
DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'BD 2',8);
END;
/
SELECT * FROM calificaciones;

--PROBAR EL PROCEDIMIENTO
DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'IA',8);
END;
/
SELECT * FROM calificaciones;--relacionado a un cursor explcito
delete from calificaciones where id_calificacion=1;--borrar
SELECT COUNT(*) FROM calificaciones;--relacionado a un cursor implicito

DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'BD 2',8);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'DMDW',7);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'JAVA 2',8);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'PDS',9);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'SIMULACION',8);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
GUARDAR_CALIFICACIONES(VALOR,'AETD',9);
END;
/

SELECT * FROM calificaciones;--relacionado a un cursor explcito
SELECT COUNT(*) FROM calificaciones;--relacionado a un cursor implicito

--EJEMPO DE CURSOR EXPLICITO CON LA TABLA CALIFICACIONES
SET SERVEROUTPUT ON; 
DECLARE
CURSOR CUR_CALIF IS SELECT * FROM CALIFICACIONES;
BEGIN 
  FOR REC IN CUR_CALIF LOOP
  DBMS_OUTPUT.PUT_LINE('CALIFICACION '||REC.VALOR|| ' MATERIA '||REC.MATERIA);
  END LOOP;
END;
/
  
  
