CREATE TABLE ALMACEN(
NUMERO_ALMACEN INTEGER,
UBICACION_ALMACEN VARCHAR2(50),
CONSTRAINT  /*Mantiene integridad en servidores*/PK_NUM_ALM PRIMARY KEY(NUMERO_ALMACEN)
);

CREATE OR REPLACE PROCEDURE GUARDAR_ALMACEN(
MY_NUMERO_ALMACEN IN integer,
MY_UBICACION_ALMACEN IN varchar2
)
AS
BEGIN 
insert into ALMACEN values (MY_NUMERO_ALMACEN,MY_UBICACION_ALMACEN);
END;
/
SELECT*FROM ALMACEN;